### ISSUE TITLE
Sometimes generated Points is extremelly low and cover a fraction of the sample region

### ISSUE THREAD

**Issue by daishishi** [udit/poisson-disc-sampling#2]
Not sure what is happening in the inner works of the code for this to happen.
Maybe is more prone in Rectangular shapes (Sample points 'stuck' in corners?), or it is because the **extremely low** number of retries (3-4).
Either way the result is only a fraction (I believe always a corner) of the shape is sampled, and only a handful of points are returned.
![Captura de tela de 2023-03-17 14-16-31](https://user-images.githubusercontent.com/7233354/225985584-5f9b49b6-30b3-47fb-b09c-a56ff43d71fc.png)

Not sure if a 'high' number of retries would solve this issue, or if it is the only option.

**Comment by udit** [comment]
3-4 retries is practically too low. You can experiment what works for your case, but 20-30 is a good number.

The algo works by randomly 'guessing' a point around an existing point till a number of 'retries', so the retries need to be sufficiently high enough otherwise you will get a sparsely generated points or hardly any points at all.

**Comment by udit** [comment]
This should work if you 1) increase "retries", and/or if you give a starting point which is not a corner. Closing this for now as there is no response. Let me know if the issue still occurs.
